.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH HOSTID-SOURCES 1  "hostid 0.1.0" "hostid Manual"
.SH NAME
hostid\-sources \- List every source identifier compiled into this binary
.SH SYNOPSIS
\fBhostid\-sources\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List every source identifier compiled into this binary
.SH OPTIONS
.TP
\fB\-\-json\fR
Emit JSON instead of one identifier per line
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
